import { abilityAccessCtrl, AbilityConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { KeyboardAvoidMode, window } from '@kit.ArkUI';
import { WeChatStore } from '../utils/chat_store';
import { UserInfoModel } from '../models/user';
import { WeChat_CurrentUserKey } from '../constants';

export default class EntryAbility extends UIAbility {
  async onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): Promise<void> {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onCreate');
    const mananger = abilityAccessCtrl.createAtManager()
    await mananger.requestPermissionsFromUser(this.context, ['ohos.permission.MICROPHONE', 'ohos.permission.LOCATION', 'ohos.permission.APPROXIMATELY_LOCATION'])
  }

  onDestroy(): void {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  async onWindowStageCreate(windowStage: window.WindowStage): Promise<void> {
    // Main window is created, set main page for this ability
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageCreate');
    WeChatStore.context = this.context
    const currentUser = WeChatStore.getCurrentUser()
    AppStorage.setOrCreate<UserInfoModel>(WeChat_CurrentUserKey, currentUser)

    windowStage.loadContent('pages/Index', async (err) => {
      if (err.code) {
        hilog.error(0x0000, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err) ?? '');
        return;
      }
      // 键盘避让
      const win = await windowStage.getMainWindow()
      win.getUIContext().setKeyboardAvoidMode(KeyboardAvoidMode.RESIZE)

      hilog.info(0x0000, 'testTag', 'Succeeded in loading the content.');
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onBackground');
  }
}
